#!/usr/bin/env python3
"""
generate_design_doc.py

Scans a reconstructed source tree (output of reconstruct_make.py) and
auto-generates figma_design.md: color tokens, typography, spacing,
component inventory, and form-validation rules — pulled from the real
code via pattern matching, not guessed.

This is intentionally conservative: it extracts what it can find with
high confidence (CSS custom properties, React component definitions,
common validation idioms) and leaves clearly-marked TODOs for anything
that needs a human/agent pass to interpret (e.g. free-form business logic).

USAGE
    python3 generate_design_doc.py <reconstructed-source-dir> <output.md>
"""

import json
import os
import re
import sys


def find_files(root, exts):
    matches = []
    for dirpath, _, filenames in os.walk(root):
        for fn in filenames:
            if any(fn.endswith(e) for e in exts):
                matches.append(os.path.join(dirpath, fn))
    return matches


def extract_css_vars(css_text):
    """Pulls :root { --token: value; } pairs, first block only (light theme)."""
    tokens = []
    root_match = re.search(r":root\s*{([^}]*)}", css_text, re.DOTALL)
    if not root_match:
        return tokens
    body = root_match.group(1)
    for line in body.split(";"):
        line = line.strip()
        m = re.match(r"(--[\w-]+)\s*:\s*(.+)", line)
        if m:
            tokens.append((m.group(1), m.group(2).strip()))
    return tokens


def extract_font_imports(css_text):
    return re.findall(r"family=([\w+]+)", css_text)


def extract_components(source_text, ext):
    names = []
    if ext in (".tsx", ".jsx", ".ts", ".js"):
        # function Foo(...) or const Foo = (...) => that look like components (capitalized)
        names += re.findall(r"function\s+([A-Z]\w*)\s*\(", source_text)
        names += re.findall(r"const\s+([A-Z]\w*)\s*=\s*\(", source_text)
        names += re.findall(r"const\s+([A-Z]\w*)\s*:\s*React\.FC", source_text)
    return sorted(set(names))


VALIDATION_PATTERNS = [
    (r"if\s*\(\s*!\w+\.trim\(\)\s*\)", "required-field (non-empty, trimmed) check"),
    (r"\.length\s*<\s*\d+", "minimum length check"),
    (r"\.length\s*>\s*\d+", "maximum length check"),
    (r"!==\s*\w*[Pp]assword|password\s*!==|!=\s*confirm", "password-match check"),
    (r"\.test\(", "regex pattern test"),
    (r"required\s*[:=]\s*true|required(?!\w)", "required attribute/flag"),
    (r"type=[\"']email[\"']", "native email type validation"),
    (r"const\s+validate\s*=", "dedicated validate() function"),
    (r"setErrors?\(", "error-state management (React)"),
]


def extract_validation_hits(source_text):
    hits = []
    for pattern, label in VALIDATION_PATTERNS:
        matches = list(re.finditer(pattern, source_text))
        if matches:
            # grab a small snippet of context for the first couple hits
            snippets = []
            for m in matches[:3]:
                start = max(0, m.start() - 40)
                end = min(len(source_text), m.end() + 40)
                snippet = source_text[start:end].replace("\n", " ").strip()
                snippets.append(snippet)
            hits.append({"pattern": label, "count": len(matches), "examples": snippets})
    return hits


def main():
    if len(sys.argv) != 3:
        print(
            "Usage: python3 generate_design_doc.py <reconstructed-source-dir> <output.md>"
        )
        sys.exit(1)

    src_dir, out_path = sys.argv[1], sys.argv[2]

    css_files = find_files(src_dir, [".css"])
    code_files = find_files(src_dir, [".tsx", ".jsx", ".ts", ".js"])

    all_tokens = []
    all_fonts = []
    for cf in css_files:
        text = open(cf, encoding="utf-8", errors="ignore").read()
        toks = extract_css_vars(text)
        if toks:
            all_tokens.append((os.path.relpath(cf, src_dir), toks))
        all_fonts += extract_font_imports(text)

    all_components = []
    all_validation = []
    for jf in code_files:
        text = open(jf, encoding="utf-8", errors="ignore").read()
        ext = os.path.splitext(jf)[1]
        comps = extract_components(text, ext)
        if comps:
            all_components.append((os.path.relpath(jf, src_dir), comps))
        hits = extract_validation_hits(text)
        if hits:
            all_validation.append((os.path.relpath(jf, src_dir), hits))
        all_fonts += re.findall(r"fontFamily:\s*[\"'`]([^\"'`]+)[\"'`]", text)

    lines = []
    lines.append("# Figma Design Reference\n")
    lines.append(
        "> Auto-generated by `generate_design_doc.py` from the reconstructed "
        "source tree. Review and refine — this is a high-confidence first pass, "
        "not a final polished spec.\n"
    )

    lines.append("## Color / Design Tokens\n")
    if all_tokens:
        for file, toks in all_tokens:
            lines.append(f"**{file}**\n")
            lines.append("| Token | Value |")
            lines.append("|---|---|")
            for name, val in toks:
                lines.append(f"| `{name}` | `{val}` |")
            lines.append("")
    else:
        lines.append(
            "<!-- No CSS custom properties found. Check for a theme file, "
            "or Tailwind config, or inline style tokens manually. -->\n"
        )

    lines.append("## Fonts\n")
    if all_fonts:
        for f in sorted(set(all_fonts)):
            lines.append(f"- {f}")
    else:
        lines.append("<!-- No font imports detected automatically. -->")
    lines.append("")

    lines.append("## Components Found\n")
    if all_components:
        for file, comps in all_components:
            lines.append(f"**{file}**: {', '.join(comps)}\n")
    else:
        lines.append("<!-- No components detected. -->\n")

    lines.append("## Validation Patterns Detected\n")
    lines.append(
        "> Each entry below is a real code pattern found via static scan. "
        "Read the surrounding function for full context before writing this "
        "up as a formal rule — these are leads, not final specs.\n"
    )
    if all_validation:
        for file, hits in all_validation:
            lines.append(f"### {file}\n")
            for h in hits:
                lines.append(f"- **{h['pattern']}** — {h['count']} occurrence(s)")
                for ex in h["examples"]:
                    lines.append(f"  - `...{ex}...`")
            lines.append("")
    else:
        lines.append(
            "<!-- No validation patterns matched. If the app has forms, "
            "check manually — validation may use a library (Zod/Yup) not "
            "covered by these regexes. -->\n"
        )

    lines.append("## Next Steps for Your Agent\n")
    lines.append(
        "- [ ] Confirm which of the detected tokens are actually used vs. "
        "leftover defaults (search each `--token` name across the codebase)."
    )
    lines.append(
        "- [ ] Group components by screen/flow and describe user-facing purpose."
    )
    lines.append(
        "- [ ] For each validation hit, write the human-readable rule and the "
        "exact trigger (on blur / on submit / live)."
    )
    lines.append(
        "- [ ] Cross-check against the live preview site to confirm final "
        "rendered behavior matches this source snapshot."
    )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Wrote {out_path}")
    print(f"  Token files found: {len(all_tokens)}")
    print(f"  Component files found: {len(all_components)}")
    print(f"  Files with validation patterns: {len(all_validation)}")


if __name__ == "__main__":
    main()
