import React from 'react'

export default function Home() {
  return (
    <section>
      <h1>Welcome</h1>
      <p>This is a minimal frontend scaffold generated by the UI/UX developer agent.</p>
    </section>
  )
}
