"""
Git hook setup script.

Installs git hooks into .git/hooks/ directory.

Hooks installed:
  - pre-commit: Validates code before commit
  - pre-push: Validates code before push
  - commit-msg: Validates commit message
"""

import os
import stat
import sys
from pathlib import Path


def get_workspace_root():
    """Get workspace root."""
    return Path(__file__).parent.parent.parent


def get_git_hooks_dir():
    """Get .git/hooks directory."""
    root = get_workspace_root()
    hooks_dir = root / ".git" / "hooks"
    
    if not hooks_dir.exists():
        print("Error: .git/hooks directory not found")
        print("Make sure you're in a git repository")
        sys.exit(1)
    
    return hooks_dir


def create_hook(hook_name, script_path, description):
    """
    Create a git hook.
    
    Args:
        hook_name: Name of hook (e.g., 'pre-commit')
        script_path: Path to Python script
        description: Human-readable description
    """
    hooks_dir = get_git_hooks_dir()
    hook_file = hooks_dir / hook_name
    
    # Hook script content
    hook_content = f"""#!/bin/bash
# Generated by scripts/hooks/setup_hooks.py
# {description}

cd "$(git rev-parse --show-toplevel)"
python scripts/hooks/{script_path}
exit $?
"""
    
    # Write hook file
    with open(hook_file, 'w') as f:
        f.write(hook_content)
    
    # Make executable
    os.chmod(hook_file, stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR | 
                        stat.S_IRGRP | stat.S_IXGRP | 
                        stat.S_IROTH | stat.S_IXOTH)
    
    print(f"✓ Installed {hook_name}")
    return True


def setup_hooks():
    """Install all git hooks."""
    print("\n╔════════════════════════════════════════╗")
    print("║      Git Hook Setup                   ║")
    print("╚════════════════════════════════════════╝\n")
    
    root = get_workspace_root()
    print(f"Workspace: {root}\n")
    
    hooks = [
        ("pre-commit", "pre_commit.py", "Validate code before commit"),
        ("pre-push", "pre_push.py", "Validate code before push"),
        ("commit-msg", "commit_msg_validator.py", "Validate commit message"),
    ]
    
    try:
        for hook_name, script_path, description in hooks:
            create_hook(hook_name, script_path, description)
        
        print("\n" + "─" * 40)
        print("✓ All hooks installed successfully\n")
        print("Hooks are now active. They will run automatically on:")
        print("  - git commit (pre-commit)")
        print("  - git push (pre-push)")
        print("  - commit message validation (commit-msg)")
        print("\nTo skip hooks in emergencies:")
        print("  git commit --no-verify")
        print("  git push --no-verify\n")
        print("To check hook logs:")
        print("  tail -f .vscode/hook-logs/*.log\n")
        return 0
        
    except Exception as e:
        print(f"\n✗ Error installing hooks: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(setup_hooks())
